// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/downloader.dart';
import 'api/types.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiDownloaderInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => 1072931690;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'fry_downloader_rust',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<bool> crateApiDownloaderCancelDownload({required String downloadId});

  Future<MediaInfo> crateApiDownloaderFetchMediaInfo({
    required String url,
    required String ytdlpPath,
  });

  Future<String> crateApiDownloaderGetYtdlpVersion({required String ytdlpPath});

  Future<void> crateApiDownloaderInitApp();

  Stream<DownloadEvent> crateApiDownloaderStartDownload({
    required String downloadId,
    required String url,
    required String formatId,
    required String outputDir,
    required String ytdlpPath,
  });
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<bool> crateApiDownloaderCancelDownload({required String downloadId}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(downloadId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiDownloaderCancelDownloadConstMeta,
        argValues: [downloadId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDownloaderCancelDownloadConstMeta =>
      const TaskConstMeta(
        debugName: "cancel_download",
        argNames: ["downloadId"],
      );

  @override
  Future<MediaInfo> crateApiDownloaderFetchMediaInfo({
    required String url,
    required String ytdlpPath,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(url, serializer);
          sse_encode_String(ytdlpPath, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_media_info,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiDownloaderFetchMediaInfoConstMeta,
        argValues: [url, ytdlpPath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDownloaderFetchMediaInfoConstMeta =>
      const TaskConstMeta(
        debugName: "fetch_media_info",
        argNames: ["url", "ytdlpPath"],
      );

  @override
  Future<String> crateApiDownloaderGetYtdlpVersion({
    required String ytdlpPath,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(ytdlpPath, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiDownloaderGetYtdlpVersionConstMeta,
        argValues: [ytdlpPath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDownloaderGetYtdlpVersionConstMeta =>
      const TaskConstMeta(
        debugName: "get_ytdlp_version",
        argNames: ["ytdlpPath"],
      );

  @override
  Future<void> crateApiDownloaderInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiDownloaderInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDownloaderInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  Stream<DownloadEvent> crateApiDownloaderStartDownload({
    required String downloadId,
    required String url,
    required String formatId,
    required String outputDir,
    required String ytdlpPath,
  }) {
    final sink = RustStreamSink<DownloadEvent>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_String(downloadId, serializer);
            sse_encode_String(url, serializer);
            sse_encode_String(formatId, serializer);
            sse_encode_String(outputDir, serializer);
            sse_encode_String(ytdlpPath, serializer);
            sse_encode_StreamSink_download_event_Sse(sink, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 5,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: null,
          ),
          constMeta: kCrateApiDownloaderStartDownloadConstMeta,
          argValues: [downloadId, url, formatId, outputDir, ytdlpPath, sink],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiDownloaderStartDownloadConstMeta =>
      const TaskConstMeta(
        debugName: "start_download",
        argNames: [
          "downloadId",
          "url",
          "formatId",
          "outputDir",
          "ytdlpPath",
          "sink",
        ],
      );

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  RustStreamSink<DownloadEvent> dco_decode_StreamSink_download_event_Sse(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  double dco_decode_box_autoadd_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  PlatformInt64 dco_decode_box_autoadd_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_i_64(raw);
  }

  @protected
  DownloadEvent dco_decode_download_event(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 9)
      throw Exception('unexpected arr length: expect 9 but see ${arr.length}');
    return DownloadEvent(
      downloadId: dco_decode_String(arr[0]),
      status: dco_decode_String(arr[1]),
      percent: dco_decode_f_64(arr[2]),
      speed: dco_decode_String(arr[3]),
      eta: dco_decode_String(arr[4]),
      downloaded: dco_decode_String(arr[5]),
      total: dco_decode_String(arr[6]),
      filePath: dco_decode_opt_String(arr[7]),
      errorMessage: dco_decode_opt_String(arr[8]),
    );
  }

  @protected
  double dco_decode_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  FormatEntry dco_decode_format_entry(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 12)
      throw Exception('unexpected arr length: expect 12 but see ${arr.length}');
    return FormatEntry(
      formatId: dco_decode_String(arr[0]),
      ext: dco_decode_String(arr[1]),
      displayName: dco_decode_String(arr[2]),
      resolution: dco_decode_opt_String(arr[3]),
      fps: dco_decode_opt_box_autoadd_f_64(arr[4]),
      vcodec: dco_decode_opt_String(arr[5]),
      acodec: dco_decode_opt_String(arr[6]),
      filesize: dco_decode_opt_box_autoadd_i_64(arr[7]),
      filesizeApprox: dco_decode_opt_box_autoadd_i_64(arr[8]),
      tbr: dco_decode_opt_box_autoadd_f_64(arr[9]),
      isAudioOnly: dco_decode_bool(arr[10]),
      isVideoOnly: dco_decode_bool(arr[11]),
    );
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  List<FormatEntry> dco_decode_list_format_entry(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_format_entry).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  MediaInfo dco_decode_media_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return MediaInfo(
      id: dco_decode_String(arr[0]),
      title: dco_decode_String(arr[1]),
      uploader: dco_decode_opt_String(arr[2]),
      duration: dco_decode_opt_box_autoadd_f_64(arr[3]),
      thumbnailUrl: dco_decode_opt_String(arr[4]),
      webpageUrl: dco_decode_String(arr[5]),
      formats: dco_decode_list_format_entry(arr[6]),
    );
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  double? dco_decode_opt_box_autoadd_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_f_64(raw);
  }

  @protected
  PlatformInt64? dco_decode_opt_box_autoadd_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_i_64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  RustStreamSink<DownloadEvent> sse_decode_StreamSink_download_event_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  double sse_decode_box_autoadd_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_f_64(deserializer));
  }

  @protected
  PlatformInt64 sse_decode_box_autoadd_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_i_64(deserializer));
  }

  @protected
  DownloadEvent sse_decode_download_event(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_downloadId = sse_decode_String(deserializer);
    var var_status = sse_decode_String(deserializer);
    var var_percent = sse_decode_f_64(deserializer);
    var var_speed = sse_decode_String(deserializer);
    var var_eta = sse_decode_String(deserializer);
    var var_downloaded = sse_decode_String(deserializer);
    var var_total = sse_decode_String(deserializer);
    var var_filePath = sse_decode_opt_String(deserializer);
    var var_errorMessage = sse_decode_opt_String(deserializer);
    return DownloadEvent(
      downloadId: var_downloadId,
      status: var_status,
      percent: var_percent,
      speed: var_speed,
      eta: var_eta,
      downloaded: var_downloaded,
      total: var_total,
      filePath: var_filePath,
      errorMessage: var_errorMessage,
    );
  }

  @protected
  double sse_decode_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat64();
  }

  @protected
  FormatEntry sse_decode_format_entry(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_formatId = sse_decode_String(deserializer);
    var var_ext = sse_decode_String(deserializer);
    var var_displayName = sse_decode_String(deserializer);
    var var_resolution = sse_decode_opt_String(deserializer);
    var var_fps = sse_decode_opt_box_autoadd_f_64(deserializer);
    var var_vcodec = sse_decode_opt_String(deserializer);
    var var_acodec = sse_decode_opt_String(deserializer);
    var var_filesize = sse_decode_opt_box_autoadd_i_64(deserializer);
    var var_filesizeApprox = sse_decode_opt_box_autoadd_i_64(deserializer);
    var var_tbr = sse_decode_opt_box_autoadd_f_64(deserializer);
    var var_isAudioOnly = sse_decode_bool(deserializer);
    var var_isVideoOnly = sse_decode_bool(deserializer);
    return FormatEntry(
      formatId: var_formatId,
      ext: var_ext,
      displayName: var_displayName,
      resolution: var_resolution,
      fps: var_fps,
      vcodec: var_vcodec,
      acodec: var_acodec,
      filesize: var_filesize,
      filesizeApprox: var_filesizeApprox,
      tbr: var_tbr,
      isAudioOnly: var_isAudioOnly,
      isVideoOnly: var_isVideoOnly,
    );
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  List<FormatEntry> sse_decode_list_format_entry(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <FormatEntry>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_format_entry(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  MediaInfo sse_decode_media_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_title = sse_decode_String(deserializer);
    var var_uploader = sse_decode_opt_String(deserializer);
    var var_duration = sse_decode_opt_box_autoadd_f_64(deserializer);
    var var_thumbnailUrl = sse_decode_opt_String(deserializer);
    var var_webpageUrl = sse_decode_String(deserializer);
    var var_formats = sse_decode_list_format_entry(deserializer);
    return MediaInfo(
      id: var_id,
      title: var_title,
      uploader: var_uploader,
      duration: var_duration,
      thumbnailUrl: var_thumbnailUrl,
      webpageUrl: var_webpageUrl,
      formats: var_formats,
    );
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  double? sse_decode_opt_box_autoadd_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_f_64(deserializer));
    } else {
      return null;
    }
  }

  @protected
  PlatformInt64? sse_decode_opt_box_autoadd_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_i_64(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_StreamSink_download_event_Sse(
    RustStreamSink<DownloadEvent> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_download_event,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_f_64(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_i_64(
    PlatformInt64 self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self, serializer);
  }

  @protected
  void sse_encode_download_event(DownloadEvent self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.downloadId, serializer);
    sse_encode_String(self.status, serializer);
    sse_encode_f_64(self.percent, serializer);
    sse_encode_String(self.speed, serializer);
    sse_encode_String(self.eta, serializer);
    sse_encode_String(self.downloaded, serializer);
    sse_encode_String(self.total, serializer);
    sse_encode_opt_String(self.filePath, serializer);
    sse_encode_opt_String(self.errorMessage, serializer);
  }

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat64(self);
  }

  @protected
  void sse_encode_format_entry(FormatEntry self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.formatId, serializer);
    sse_encode_String(self.ext, serializer);
    sse_encode_String(self.displayName, serializer);
    sse_encode_opt_String(self.resolution, serializer);
    sse_encode_opt_box_autoadd_f_64(self.fps, serializer);
    sse_encode_opt_String(self.vcodec, serializer);
    sse_encode_opt_String(self.acodec, serializer);
    sse_encode_opt_box_autoadd_i_64(self.filesize, serializer);
    sse_encode_opt_box_autoadd_i_64(self.filesizeApprox, serializer);
    sse_encode_opt_box_autoadd_f_64(self.tbr, serializer);
    sse_encode_bool(self.isAudioOnly, serializer);
    sse_encode_bool(self.isVideoOnly, serializer);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_list_format_entry(
    List<FormatEntry> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_format_entry(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_media_info(MediaInfo self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.title, serializer);
    sse_encode_opt_String(self.uploader, serializer);
    sse_encode_opt_box_autoadd_f_64(self.duration, serializer);
    sse_encode_opt_String(self.thumbnailUrl, serializer);
    sse_encode_String(self.webpageUrl, serializer);
    sse_encode_list_format_entry(self.formats, serializer);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_f_64(double? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_f_64(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_i_64(
    PlatformInt64? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_i_64(self, serializer);
    }
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }
}
