// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'types.dart';

// These functions are ignored because they are not marked as `pub`: `build_display_name`, `format_downloaded`, `human_bytes`, `parse_format_entry`, `parse_media_info`

/// Return the installed yt-dlp version string, or an error message.
Future<String> getYtdlpVersion({required String ytdlpPath}) => RustLib
    .instance
    .api
    .crateApiDownloaderGetYtdlpVersion(ytdlpPath: ytdlpPath);

/// Fetch metadata (title, formats, …) for the given URL.
Future<MediaInfo> fetchMediaInfo({
  required String url,
  required String ytdlpPath,
}) => RustLib.instance.api.crateApiDownloaderFetchMediaInfo(
  url: url,
  ytdlpPath: ytdlpPath,
);

/// Start downloading a URL with the given format.
///
/// Progress events are streamed via `sink` until completion, cancellation, or
/// an error.  The download can be cancelled by calling [`cancel_download`]
/// with the same `download_id`.
Stream<DownloadEvent> startDownload({
  required String downloadId,
  required String url,
  required String formatId,
  required String outputDir,
  required String ytdlpPath,
}) => RustLib.instance.api.crateApiDownloaderStartDownload(
  downloadId: downloadId,
  url: url,
  formatId: formatId,
  outputDir: outputDir,
  ytdlpPath: ytdlpPath,
);

/// Cancel a running download.  Returns `true` if the process was found and
/// killed, `false` if no download with that ID was active.
Future<bool> cancelDownload({required String downloadId}) => RustLib
    .instance
    .api
    .crateApiDownloaderCancelDownload(downloadId: downloadId);
