// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// An event emitted while a download is in progress.
class DownloadEvent {
  final String downloadId;
  final String status;

  /// 0.0 – 100.0
  final double percent;

  /// Human-readable speed, e.g. "1.23 MiB/s"
  final String speed;

  /// Human-readable ETA, e.g. "00:04"
  final String eta;

  /// Human-readable amount downloaded, e.g. "5.00MiB"
  final String downloaded;

  /// Human-readable total size, e.g. "10.00MiB"
  final String total;

  /// Set on completion.
  final String? filePath;

  /// Set on error.
  final String? errorMessage;

  const DownloadEvent({
    required this.downloadId,
    required this.status,
    required this.percent,
    required this.speed,
    required this.eta,
    required this.downloaded,
    required this.total,
    this.filePath,
    this.errorMessage,
  });

  @override
  int get hashCode =>
      downloadId.hashCode ^
      status.hashCode ^
      percent.hashCode ^
      speed.hashCode ^
      eta.hashCode ^
      downloaded.hashCode ^
      total.hashCode ^
      filePath.hashCode ^
      errorMessage.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DownloadEvent &&
          runtimeType == other.runtimeType &&
          downloadId == other.downloadId &&
          status == other.status &&
          percent == other.percent &&
          speed == other.speed &&
          eta == other.eta &&
          downloaded == other.downloaded &&
          total == other.total &&
          filePath == other.filePath &&
          errorMessage == other.errorMessage;
}

/// A single downloadable format entry.
class FormatEntry {
  final String formatId;
  final String ext;

  /// Human-readable label, e.g. "1080p (mp4)", "Audio only (m4a)".
  final String displayName;
  final String? resolution;
  final double? fps;
  final String? vcodec;
  final String? acodec;

  /// Exact filesize in bytes if known.
  final PlatformInt64? filesize;

  /// Approximate filesize in bytes.
  final PlatformInt64? filesizeApprox;

  /// Total bitrate kbps.
  final double? tbr;
  final bool isAudioOnly;
  final bool isVideoOnly;

  const FormatEntry({
    required this.formatId,
    required this.ext,
    required this.displayName,
    this.resolution,
    this.fps,
    this.vcodec,
    this.acodec,
    this.filesize,
    this.filesizeApprox,
    this.tbr,
    required this.isAudioOnly,
    required this.isVideoOnly,
  });

  @override
  int get hashCode =>
      formatId.hashCode ^
      ext.hashCode ^
      displayName.hashCode ^
      resolution.hashCode ^
      fps.hashCode ^
      vcodec.hashCode ^
      acodec.hashCode ^
      filesize.hashCode ^
      filesizeApprox.hashCode ^
      tbr.hashCode ^
      isAudioOnly.hashCode ^
      isVideoOnly.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FormatEntry &&
          runtimeType == other.runtimeType &&
          formatId == other.formatId &&
          ext == other.ext &&
          displayName == other.displayName &&
          resolution == other.resolution &&
          fps == other.fps &&
          vcodec == other.vcodec &&
          acodec == other.acodec &&
          filesize == other.filesize &&
          filesizeApprox == other.filesizeApprox &&
          tbr == other.tbr &&
          isAudioOnly == other.isAudioOnly &&
          isVideoOnly == other.isVideoOnly;
}

/// Info returned by yt-dlp --dump-json for a URL.
class MediaInfo {
  final String id;
  final String title;
  final String? uploader;

  /// Duration in seconds.
  final double? duration;
  final String? thumbnailUrl;
  final String webpageUrl;
  final List<FormatEntry> formats;

  const MediaInfo({
    required this.id,
    required this.title,
    this.uploader,
    this.duration,
    this.thumbnailUrl,
    required this.webpageUrl,
    required this.formats,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      title.hashCode ^
      uploader.hashCode ^
      duration.hashCode ^
      thumbnailUrl.hashCode ^
      webpageUrl.hashCode ^
      formats.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MediaInfo &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          title == other.title &&
          uploader == other.uploader &&
          duration == other.duration &&
          thumbnailUrl == other.thumbnailUrl &&
          webpageUrl == other.webpageUrl &&
          formats == other.formats;
}
